backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "products"
    label: "Products"
    folder: "src/content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Header Variant", name: "headerVariant", widget: "select", options: ["default", "product"] }
      - { label: "Body", name: "body", widget: "markdown" }
